
namespace ESRI.ArcGIS.OSM.Editor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OSMFeatureInspectorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OSMFeatureInspectorStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESRI.ArcGIS.OSM.Editor.OSMFeatureInspectorStrings", typeof(OSMFeatureInspectorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string OSMEditor_Authentication_UI_labelpassword {
            get {
                return ResourceManager.GetString("OSMEditor_Authentication_UI_labelpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        internal static string OSMEditor_Authentication_UI_labelusername {
            get {
                return ResourceManager.GetString("OSMEditor_Authentication_UI_labelusername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSM Conflict Editor.
        /// </summary>
        internal static string OSMEditor_ConflictEditor_caption {
            get {
                return ResourceManager.GetString("OSMEditor_ConflictEditor_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenStreetMap.
        /// </summary>
        internal static string OSMEditor_ConflictEditor_category {
            get {
                return ResourceManager.GetString("OSMEditor_ConflictEditor_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset the current revision status.
        /// </summary>
        internal static string OSMEditor_ConflictEditor_error_clearRevisionStatus {
            get {
                return ResourceManager.GetString("OSMEditor_ConflictEditor_error_clearRevisionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the revision incident.
        /// </summary>
        internal static string OSMEditor_ConflictEditor_error_removeRevisionIncident {
            get {
                return ResourceManager.GetString("OSMEditor_ConflictEditor_error_removeRevisionIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No known solution for this error.
        /// </summary>
        internal static string OSMEditor_ConflictEditor_error_UnknownSolution {
            get {
                return ResourceManager.GetString("OSMEditor_ConflictEditor_error_UnknownSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete local feature.
        /// </summary>
        internal static string OSMEditor_ConflictEditor_error404_deletelocal {
            get {
                return ResourceManager.GetString("OSMEditor_ConflictEditor_error404_deletelocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep local attributes and server geometry.
        /// </summary>
        internal static string OSMEditor_ConflictEditor_error409_keepLocalAttributesServerGeometry {
            get {
                return ResourceManager.GetString("OSMEditor_ConflictEditor_error409_keepLocalAttributesServerGeometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep local geometry and local attributes.
        /// </summary>
        internal static string OSMEditor_ConflictEditor_error409_keepLocalGeometryAttributes {
            get {
                return ResourceManager.GetString("OSMEditor_ConflictEditor_error409_keepLocalGeometryAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep local geometry and server attributes.
        /// </summary>
        internal static string OSMEditor_ConflictEditor_error409_keepLocalGeometryServerAttributes {
            get {
                return ResourceManager.GetString("OSMEditor_ConflictEditor_error409_keepLocalGeometryServerAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep server geometry and server attributes.
        /// </summary>
        internal static string OSMEditor_ConflictEditor_error409_keepServerGeometryServerAttributes {
            get {
                return ResourceManager.GetString("OSMEditor_ConflictEditor_error409_keepServerGeometryServerAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete local feature.
        /// </summary>
        internal static string OSMEditor_ConflictEditor_error410_deletelocal {
            get {
                return ResourceManager.GetString("OSMEditor_ConflictEditor_error410_deletelocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSM Conflict Editor.
        /// </summary>
        internal static string OSMEditor_ConflictEditor_formtitle {
            get {
                return ResourceManager.GetString("OSMEditor_ConflictEditor_formtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict Operation.
        /// </summary>
        internal static string OSMEditor_ConflictEditor_genericConflictOpMessage {
            get {
                return ResourceManager.GetString("OSMEditor_ConflictEditor_genericConflictOpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local OSM Feature.
        /// </summary>
        internal static string OSMEditor_ConflictEditor_localOSMFeature_header {
            get {
                return ResourceManager.GetString("OSMEditor_ConflictEditor_localOSMFeature_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the OpenStreetMap Conflict Editor.
        /// </summary>
        internal static string OSMEditor_ConflictEditor_message {
            get {
                return ResourceManager.GetString("OSMEditor_ConflictEditor_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No revision tables found in current data frame. Please be sure to have OSM feature classes or revision tables loaded..
        /// </summary>
        internal static string OSMEditor_ConflictEditor_norevisionTables {
            get {
                return ResourceManager.GetString("OSMEditor_ConflictEditor_norevisionTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Information.
        /// </summary>
        internal static string OSMEditor_ConflictEditor_norevisionTables_title {
            get {
                return ResourceManager.GetString("OSMEditor_ConflictEditor_norevisionTables_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSM Attributes.
        /// </summary>
        internal static string OSMEditor_ConflictEditor_osmattributes_header {
            get {
                return ResourceManager.GetString("OSMEditor_ConflictEditor_osmattributes_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string OSMEditor_ConflictEditor_osmtypedescription_ln {
            get {
                return ResourceManager.GetString("OSMEditor_ConflictEditor_osmtypedescription_ln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polygon.
        /// </summary>
        internal static string OSMEditor_ConflictEditor_osmtypedescription_ply {
            get {
                return ResourceManager.GetString("OSMEditor_ConflictEditor_osmtypedescription_ply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point.
        /// </summary>
        internal static string OSMEditor_ConflictEditor_osmtypedescription_pt {
            get {
                return ResourceManager.GetString("OSMEditor_ConflictEditor_osmtypedescription_pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation.
        /// </summary>
        internal static string OSMEditor_ConflictEditor_osmtypedescription_relation {
            get {
                return ResourceManager.GetString("OSMEditor_ConflictEditor_osmtypedescription_relation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string OSMEditor_ConflictEditor_osmtypedescription_unk {
            get {
                return ResourceManager.GetString("OSMEditor_ConflictEditor_osmtypedescription_unk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing and collecting data differences.
        /// </summary>
        internal static string OSMEditor_ConflictEditor_prepareCollectData {
            get {
                return ResourceManager.GetString("OSMEditor_ConflictEditor_prepareCollectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server OSM Feature.
        /// </summary>
        internal static string OSMEditor_ConflictEditor_serverOSMFeature_header {
            get {
                return ResourceManager.GetString("OSMEditor_ConflictEditor_serverOSMFeature_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the OpenStreetMap Conflict Editor.
        /// </summary>
        internal static string OSMEditor_ConflictEditor_tooltip {
            get {
                return ResourceManager.GetString("OSMEditor_ConflictEditor_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error storing OSM settings.
        /// </summary>
        internal static string OSMEditor_Extension_storesettingsproblem {
            get {
                return ResourceManager.GetString("OSMEditor_Extension_storesettingsproblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry Conflict.
        /// </summary>
        internal static string OSMEditor_FeatureInspector_geometryconflictcaption {
            get {
                return ResourceManager.GetString("OSMEditor_FeatureInspector_geometryconflictcaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feature you created contains more than 2000 nodes. In order to generate OSM conform data you need to split the data separate geometries. If you press OK please use the split tool to split the geometry into smaller segments, otherwise the current feature will be deleted..
        /// </summary>
        internal static string OSMEditor_FeatureInspector_morethan2000 {
            get {
                return ResourceManager.GetString("OSMEditor_FeatureInspector_morethan2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feature geometry contains multiple parts. If you press OK you need to take this geometry through the multipart to singlepart geoporcessing tool, otherwise the current feature will be deleted..
        /// </summary>
        internal static string OSMEditor_FeatureInspector_multipart {
            get {
                return ResourceManager.GetString("OSMEditor_FeatureInspector_multipart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feature (OSMID: {0}) you are attempting to change is a member of relation ({1}). This action is currently not supported and the edit operation is aborted..
        /// </summary>
        internal static string OSMEditor_FeatureInspector_multipartchangeconflictmessage {
            get {
                return ResourceManager.GetString("OSMEditor_FeatureInspector_multipartchangeconflictmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feature (OSMID: {0}) you are attempting to change is a relation. This action is currently not supported and the edit operation is aborted..
        /// </summary>
        internal static string OSMEditor_FeatureInspector_multipartchangeparentconflictmessage {
            get {
                return ResourceManager.GetString("OSMEditor_FeatureInspector_multipartchangeparentconflictmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feature (OSMID: {0}) you are attempting to delete is a member of relation ({1}). This action is currently not supported and the edit operation is aborted..
        /// </summary>
        internal static string OSMEditor_FeatureInspector_multipartdeleteconflictmessage {
            get {
                return ResourceManager.GetString("OSMEditor_FeatureInspector_multipartdeleteconflictmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feature (OSMID: {0}) you are attempting to delete is a relation. This action is currently not supported and the edit operation is aborted..
        /// </summary>
        internal static string OSMEditor_FeatureInspector_multipartdeleteparentconflictmessage {
            get {
                return ResourceManager.GetString("OSMEditor_FeatureInspector_multipartdeleteparentconflictmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSM Attribute Change.
        /// </summary>
        internal static string OSMEditor_FeatureInspector_operationmenu {
            get {
                return ResourceManager.GetString("OSMEditor_FeatureInspector_operationmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit operation in progress.
        /// </summary>
        internal static string OSMEditor_FeatureInspector_operationwarningcaption {
            get {
                return ResourceManager.GetString("OSMEditor_FeatureInspector_operationwarningcaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to finish the current operation first, before you can change any attributes. .
        /// </summary>
        internal static string OSMEditor_FeatureInspector_operationwarningtext {
            get {
                return ResourceManager.GetString("OSMEditor_FeatureInspector_operationwarningtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point ID:.
        /// </summary>
        internal static string OSMEditor_FeatureInspector_pointidtext {
            get {
                return ResourceManager.GetString("OSMEditor_FeatureInspector_pointidtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are attempting to delete a point that is referenced by a relation (OSMID: {0}). This action is currently not supported and the edit operation is aborted..
        /// </summary>
        internal static string OSMEditor_FeatureInspector_pointmemberofrelation {
            get {
                return ResourceManager.GetString("OSMEditor_FeatureInspector_pointmemberofrelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The polygon geometry exceeds the number of allowed points ({0}) in geometry part {1}..
        /// </summary>
        internal static string OSMEditor_FeatureInspector_pointnumber_exceeeded_in_ring {
            get {
                return ResourceManager.GetString("OSMEditor_FeatureInspector_pointnumber_exceeeded_in_ring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polygon ID: .
        /// </summary>
        internal static string OSMEditor_FeatureInspector_polygonidtext {
            get {
                return ResourceManager.GetString("OSMEditor_FeatureInspector_polygonidtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyline ID: .
        /// </summary>
        internal static string OSMEditor_FeatureInspector_polylineidtext {
            get {
                return ResourceManager.GetString("OSMEditor_FeatureInspector_polylineidtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation Conflict.
        /// </summary>
        internal static string OSMEditor_FeatureInspector_relationconflictcaption {
            get {
                return ResourceManager.GetString("OSMEditor_FeatureInspector_relationconflictcaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feature (OSMID: {0}) you are attempting to delete is a member of a relation (OSMID: {1}). If you continue, the editor will remove the feature from the relation, otherwise the delete operation will be undone..
        /// </summary>
        internal static string OSMEditor_FeatureInspector_relationconflictmessage {
            get {
                return ResourceManager.GetString("OSMEditor_FeatureInspector_relationconflictmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation ID: .
        /// </summary>
        internal static string OSMEditor_FeatureInspector_relationidtext {
            get {
                return ResourceManager.GetString("OSMEditor_FeatureInspector_relationidtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feature (OSMID: {0}) you are attempting to delete is a member of relations (OSMIDs: {1}). If you continue, the editor will remove the feature from the relations, otherwise the delete operation will be undone..
        /// </summary>
        internal static string OSMEditor_FeatureInspector_relationsconflictmessage {
            get {
                return ResourceManager.GetString("OSMEditor_FeatureInspector_relationsconflictmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Files.
        /// </summary>
        internal static string OSMEditor_GxFilterXmlFiles_description {
            get {
                return ResourceManager.GetString("OSMEditor_GxFilterXmlFiles_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string OSMEditor_LicenseAlertDialog_Cancel {
            get {
                return ResourceManager.GetString("OSMEditor_LicenseAlertDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///You are about to edit data that is licensed under the Open Database License 1.0 from OpenStreetMap - see http://www.osmfoundation.org/wiki/License/Contributor_Terms. 
        ///
        ///When you press the OK button you are agreeing that you are the original creator for the new data and that you have all the necessary permissions should you derive (copy/trace/duplicate/import) data from existing data sources. If in doubt, please press Cancel and obtain legal advice about data licensing or post a question at the OSM lega [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OSMEditor_LicenseAlertDialog_LicenseAlert {
            get {
                return ResourceManager.GetString("OSMEditor_LicenseAlertDialog_LicenseAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 109,59,http://www.osmfoundation.org/wiki/License/Contributor_Terms;503,15,http://lists.openstreetmap.org/listinfo/legal-talk.
        /// </summary>
        internal static string OSMEditor_LicenseAlertDialog_LicenseAlertLink {
            get {
                return ResourceManager.GetString("OSMEditor_LicenseAlertDialog_LicenseAlertLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OSMEditor_LicenseAlertDialog_OK {
            get {
                return ResourceManager.GetString("OSMEditor_LicenseAlertDialog_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSM License Confirmation.
        /// </summary>
        internal static string OSMEditor_LicenseAlertDialog_Title {
            get {
                return ResourceManager.GetString("OSMEditor_LicenseAlertDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string OSMEditor_OSMPropertyPage_fileselect_buttoncaption {
            get {
                return ResourceManager.GetString("OSMEditor_OSMPropertyPage_fileselect_buttoncaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select OSM Domain XML File.
        /// </summary>
        internal static string OSMEditor_OSMPropertyPage_fileselect_title_domain {
            get {
                return ResourceManager.GetString("OSMEditor_OSMPropertyPage_fileselect_title_domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select OSM Feature XML File.
        /// </summary>
        internal static string OSMEditor_OSMPropertyPage_fileselect_title_feature {
            get {
                return ResourceManager.GetString("OSMEditor_OSMPropertyPage_fileselect_title_feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSM base URL:.
        /// </summary>
        internal static string OSMEditor_OSMPropertyPage_labelBaseURL {
            get {
                return ResourceManager.GetString("OSMEditor_OSMPropertyPage_labelBaseURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSM Domains:.
        /// </summary>
        internal static string OSMEditor_OSMPropertyPage_labelOSMDomains {
            get {
                return ResourceManager.GetString("OSMEditor_OSMPropertyPage_labelOSMDomains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSM Features:.
        /// </summary>
        internal static string OSMEditor_OSMPropertyPage_labelOSMFeatures {
            get {
                return ResourceManager.GetString("OSMEditor_OSMPropertyPage_labelOSMFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenStreetMap.
        /// </summary>
        internal static string OSMEditor_OSMPropertyPage_tabtitle {
            get {
                return ResourceManager.GetString("OSMEditor_OSMPropertyPage_tabtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenStreetMap.
        /// </summary>
        internal static string OSMEditor_OSMToolbar_Caption {
            get {
                return ResourceManager.GetString("OSMEditor_OSMToolbar_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenStreetMap.
        /// </summary>
        internal static string OSMEditor_OSMToolbarCmd_caption {
            get {
                return ResourceManager.GetString("OSMEditor_OSMToolbarCmd_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open/Close the OSM Toolbar.
        /// </summary>
        internal static string OSMEditor_OSMToolbarCmd_message {
            get {
                return ResourceManager.GetString("OSMEditor_OSMToolbarCmd_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open/Close the OSM Toolbar.
        /// </summary>
        internal static string OSMEditor_OSMToolbarCmd_tooltip {
            get {
                return ResourceManager.GetString("OSMEditor_OSMToolbarCmd_tooltip", resourceCulture);
            }
        }
    }
}
