//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace ESRI.ArcGIS.OSM.GeoProcessing {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class networkConfiguration {
        
        private edge[] edgeField;
        
        private junction[] junctionField;
        
        private turn[] turnField;
        
        private string[][] connectivityField;
        
        private network_attribute[][] networkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("edge")]
        public edge[] edge {
            get {
                return this.edgeField;
            }
            set {
                this.edgeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("junction")]
        public junction[] junction {
            get {
                return this.junctionField;
            }
            set {
                this.junctionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("turn")]
        public turn[] turn {
            get {
                return this.turnField;
            }
            set {
                this.turnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("group", IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("name", IsNullable=false, NestingLevel=1)]
        public string[][] connectivity {
            get {
                return this.connectivityField;
            }
            set {
                this.connectivityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("network_attribute", typeof(network_attribute), IsNullable=false)]
        public network_attribute[][] network {
            get {
                return this.networkField;
            }
            set {
                this.networkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class edge {
        
        private string nameField;
        
        private string[] queryField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("query", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class junction {
        
        private string nameField;
        
        private string[] queryField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("query", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class turn {
        
        private string nameField;
        
        private string[] queryField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("query", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class network_attribute {
        
        private string nameField;
        
        private object itemField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cost", typeof(cost))]
        [System.Xml.Serialization.XmlElementAttribute("descriptor", typeof(descriptor))]
        [System.Xml.Serialization.XmlElementAttribute("hierachy", typeof(hierachy))]
        [System.Xml.Serialization.XmlElementAttribute("restriction", typeof(restriction))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class cost {
        
        private units unitsField;
        
        private datatype datatypeField;
        
        private evaluator_attributes[] evaluator_attributesField;
        
        private bool useAsDefaultField;
        
        private bool useAsDefaultFieldSpecified;
        
        /// <remarks/>
        public units units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
            }
        }
        
        /// <remarks/>
        public datatype datatype {
            get {
                return this.datatypeField;
            }
            set {
                this.datatypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("evaluator_attributes")]
        public evaluator_attributes[] evaluator_attributes {
            get {
                return this.evaluator_attributesField;
            }
            set {
                this.evaluator_attributesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool useAsDefault {
            get {
                return this.useAsDefaultField;
            }
            set {
                this.useAsDefaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool useAsDefaultSpecified {
            get {
                return this.useAsDefaultFieldSpecified;
            }
            set {
                this.useAsDefaultFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public enum units {
        
        /// <remarks/>
        esriNAUUnknown,
        
        /// <remarks/>
        esriNAUInches,
        
        /// <remarks/>
        esriNAUFeet,
        
        /// <remarks/>
        esriNAUYards,
        
        /// <remarks/>
        esriNAUMiles,
        
        /// <remarks/>
        esriNAUNauticalMiles,
        
        /// <remarks/>
        esriNAUMillimeters,
        
        /// <remarks/>
        esriNAUCentimeters,
        
        /// <remarks/>
        esriNAUMeters,
        
        /// <remarks/>
        esriNAUKilometers,
        
        /// <remarks/>
        esriNAUDecimalDegrees,
        
        /// <remarks/>
        esriNAUDecimeters,
        
        /// <remarks/>
        esriNAUSeconds,
        
        /// <remarks/>
        esriNAUMinutes,
        
        /// <remarks/>
        esriNAUHours,
        
        /// <remarks/>
        esriNAUDays,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public enum datatype {
        
        /// <remarks/>
        @bool,
        
        /// <remarks/>
        @double,
        
        /// <remarks/>
        @int,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class evaluator_attributes {
        
        private string sourceField;
        
        private direction directionField;
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public direction direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Constant", typeof(Constant))]
        [System.Xml.Serialization.XmlElementAttribute("Field", typeof(Field))]
        [System.Xml.Serialization.XmlElementAttribute("Function", typeof(Function))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public enum direction {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("From-To")]
        FromTo,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("To-From")]
        ToFrom,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Constant {
        
        private object valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Field {
        
        private string keyField;
        
        private string pre_logicField;
        
        private FieldScript_type script_typeField;
        
        private bool script_typeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pre_logic {
            get {
                return this.pre_logicField;
            }
            set {
                this.pre_logicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public FieldScript_type script_type {
            get {
                return this.script_typeField;
            }
            set {
                this.script_typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool script_typeSpecified {
            get {
                return this.script_typeFieldSpecified;
            }
            set {
                this.script_typeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum FieldScript_type {
        
        /// <remarks/>
        VBScript,
        
        /// <remarks/>
        Python,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Function {
        
        private string nameField;
        
        private string function_stringField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string function_string {
            get {
                return this.function_stringField;
            }
            set {
                this.function_stringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class descriptor {
        
        private datatype datatypeField;
        
        private evaluator_attributes[] evaluator_attributesField;
        
        private bool useAsDefaultField;
        
        private bool useAsDefaultFieldSpecified;
        
        /// <remarks/>
        public datatype datatype {
            get {
                return this.datatypeField;
            }
            set {
                this.datatypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("evaluator_attributes")]
        public evaluator_attributes[] evaluator_attributes {
            get {
                return this.evaluator_attributesField;
            }
            set {
                this.evaluator_attributesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool useAsDefault {
            get {
                return this.useAsDefaultField;
            }
            set {
                this.useAsDefaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool useAsDefaultSpecified {
            get {
                return this.useAsDefaultFieldSpecified;
            }
            set {
                this.useAsDefaultFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class hierachy {
        
        private evaluator_attributes[] evaluator_attributesField;
        
        private bool useAsDefaultField;
        
        private bool useAsDefaultFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("evaluator_attributes")]
        public evaluator_attributes[] evaluator_attributes {
            get {
                return this.evaluator_attributesField;
            }
            set {
                this.evaluator_attributesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool useAsDefault {
            get {
                return this.useAsDefaultField;
            }
            set {
                this.useAsDefaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool useAsDefaultSpecified {
            get {
                return this.useAsDefaultFieldSpecified;
            }
            set {
                this.useAsDefaultFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class restriction {
        
        private evaluator_attributes[] evaluator_attributesField;
        
        private bool useAsDefaultField;
        
        private bool useAsDefaultFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("evaluator_attributes")]
        public evaluator_attributes[] evaluator_attributes {
            get {
                return this.evaluator_attributesField;
            }
            set {
                this.evaluator_attributesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool useAsDefault {
            get {
                return this.useAsDefaultField;
            }
            set {
                this.useAsDefaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool useAsDefaultSpecified {
            get {
                return this.useAsDefaultFieldSpecified;
            }
            set {
                this.useAsDefaultFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class connectivity {
        
        private string[][] groupField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("name", typeof(string), IsNullable=false)]
        public string[][] group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class group {
        
        private string[] nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("name")]
        public string[] name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class network {
        
        private network_attribute[] network_attributeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("network_attribute")]
        public network_attribute[] network_attribute {
            get {
                return this.network_attributeField;
            }
            set {
                this.network_attributeField = value;
            }
        }
    }
}
