// (c) Copyright Esri, 2010 - 2016
// This source is subject to the Apache 2.0 License.
// Please see http://www.apache.org/licenses/LICENSE-2.0.html for details.
// All other rights reserved.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace ESRI.ArcGIS.OSM.OSMClassExtension {
	using System.Xml.Serialization;
	using System.Runtime.InteropServices;
	
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
	[ComVisible(false)]
	public partial class api {
		
		private version versionField;
		
		private area areaField;
		
		private tracepoints tracepointsField;
		
		private waynodes waynodesField;
		
		private changesets changesetsField;
		
		private timeout timeoutField;
		
		/// <remarks/>
		public version version {
			get {
				return this.versionField;
			}
			set {
				this.versionField = value;
			}
		}
		
		/// <remarks/>
		public area area {
			get {
				return this.areaField;
			}
			set {
				this.areaField = value;
			}
		}
		
		/// <remarks/>
		public tracepoints tracepoints {
			get {
				return this.tracepointsField;
			}
			set {
				this.tracepointsField = value;
			}
		}
		
		/// <remarks/>
		public waynodes waynodes {
			get {
				return this.waynodesField;
			}
			set {
				this.waynodesField = value;
			}
		}
		
		/// <remarks/>
		public changesets changesets {
			get {
				return this.changesetsField;
			}
			set {
				this.changesetsField = value;
			}
		}
		
		/// <remarks/>
		public timeout timeout {
			get {
				return this.timeoutField;
			}
			set {
				this.timeoutField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
	[ComVisible(false)]
	public partial class version {
		
		private string minimumField;
		
		private string maximumField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string minimum {
			get {
				return this.minimumField;
			}
			set {
				this.minimumField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string maximum {
			get {
				return this.maximumField;
			}
			set {
				this.maximumField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
	[ComVisible(false)]
	public partial class area {
		
		private string maximumField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string maximum {
			get {
				return this.maximumField;
			}
			set {
				this.maximumField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
	[ComVisible(false)]
	public partial class tracepoints {
		
		private string per_pageField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string per_page {
			get {
				return this.per_pageField;
			}
			set {
				this.per_pageField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
	[ComVisible(false)]
	public partial class waynodes {
		
		private string maximumField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string maximum {
			get {
				return this.maximumField;
			}
			set {
				this.maximumField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
	[ComVisible(false)]
	public partial class changesets {
		
		private string maximum_elementsField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string maximum_elements {
			get {
				return this.maximum_elementsField;
			}
			set {
				this.maximum_elementsField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
	[ComVisible(false)]
	public partial class timeout {
		
		private string secondsField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string seconds {
			get {
				return this.secondsField;
			}
			set {
				this.secondsField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
	[ComVisible(false)]
	public partial class changeset {
		
		private tag[] tagField;
		
		private string idField;
		
		private changesetOpen openField;
		
		public changeset() {
			this.openField = changesetOpen.@false;
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("tag")]
		public tag[] tag {
			get {
				return this.tagField;
			}
			set {
				this.tagField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string id {
			get {
				return this.idField;
			}
			set {
				this.idField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.DefaultValueAttribute(changesetOpen.@false)]
		public changesetOpen open {
			get {
				return this.openField;
			}
			set {
				this.openField = value;
			}
		}
	}
	
	/// <remarks/>
	public partial class tag {
		
		private string vField;
		
		private string kField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string k
		{
			get
			{
				return this.kField;
			}
			set
			{
				this.kField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string v {
			get {
				return this.vField;
			}
			set {
				this.vField = value;
			}
		}
		
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	[ComVisible(false)]
	public enum changesetOpen {
		
		/// <remarks/>
		@true,
		
		/// <remarks/>
		@false,
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
	[ComVisible(false)]
	public partial class gpx_file {
		
		private string userField;
		
		private string nameField;
		
		private string timestampField;
		
		private string latField;
		
		private gpx_filePending pendingField;
		
		private gpx_filePublic publicField;
		
		private string lonField;
		
		private string idField;
		
		public gpx_file() {
			this.pendingField = gpx_filePending.@false;
			this.publicField = gpx_filePublic.@false;
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string user {
			get {
				return this.userField;
			}
			set {
				this.userField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string name {
			get {
				return this.nameField;
			}
			set {
				this.nameField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string timestamp {
			get {
				return this.timestampField;
			}
			set {
				this.timestampField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string lat {
			get {
				return this.latField;
			}
			set {
				this.latField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.DefaultValueAttribute(gpx_filePending.@false)]
		public gpx_filePending pending {
			get {
				return this.pendingField;
			}
			set {
				this.pendingField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.DefaultValueAttribute(gpx_filePublic.@false)]
		public gpx_filePublic @public {
			get {
				return this.publicField;
			}
			set {
				this.publicField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string lon {
			get {
				return this.lonField;
			}
			set {
				this.lonField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string id {
			get {
				return this.idField;
			}
			set {
				this.idField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	[ComVisible(false)]
	public enum gpx_filePending {
		
		/// <remarks/>
		@true,
		
		/// <remarks/>
		@false,
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	[ComVisible(false)]
	public enum gpx_filePublic {
		
		/// <remarks/>
		@true,
		
		/// <remarks/>
		@false,
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
	[ComVisible(false)]
	public partial class home {
		
		private string zoomField;
		
		private string latField;
		
		private string lonField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string zoom {
			get {
				return this.zoomField;
			}
			set {
				this.zoomField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string lat {
			get {
				return this.latField;
			}
			set {
				this.latField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string lon {
			get {
				return this.lonField;
			}
			set {
				this.lonField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
	[ComVisible(false)]
	public partial class member {
		
		private memberType typeField;
		
		private string refField;
		
		private string roleField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public memberType type {
			get {
				return this.typeField;
			}
			set {
				this.typeField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string @ref {
			get {
				return this.refField;
			}
			set {
				this.refField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string role {
			get {
				return this.roleField;
			}
			set {
				this.roleField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	[ComVisible(false)]
	public enum memberType {
		
		/// <remarks/>
		way,
		
		/// <remarks/>
		node,
		
		/// <remarks/>
		relation,
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
	[ComVisible(false)]
	public partial class nd {
		
		private string refField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string @ref {
			get {
				return this.refField;
			}
			set {
				this.refField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
	[ComVisible(false)]
	public partial class bounds {
		
		private double minlatField;
		
		private double minlonField;
		
		private double maxlatField;
		
		private double maxlonField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public double minlat {
			get {
				return this.minlatField;
			}
			set {
				this.minlatField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public double minlon {
			get {
				return this.minlonField;
			}
			set {
				this.minlonField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public double maxlat {
			get {
				return this.maxlatField;
			}
			set {
				this.maxlatField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public double maxlon {
			get {
				return this.maxlonField;
			}
			set {
				this.maxlonField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
	[ComVisible(false)]
	public partial class node {
		
		private tag[] tagField;
		
		private string userField;
		
		private string uidField;
		
		private string timestampField;
		
		private string latField;
		
		private nodeVisible visibleField;
		
		private string lonField;
		
		private string changesetField;
		
		private string versionField;
		
		private string idField;


		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string id
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string lat
		{
			get
			{
				return this.latField;
			}
			set
			{
				this.latField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string lon
		{
			get
			{
				return this.lonField;
			}
			set
			{
				this.lonField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("tag")]
		public tag[] tag {
			get {
				return this.tagField;
			}
			set {
				this.tagField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string user {
			get {
				return this.userField;
			}
			set {
				this.userField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string uid {
			get {
				return this.uidField;
			}
			set {
				this.uidField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string timestamp {
			get {
				return this.timestampField;
			}
			set {
				this.timestampField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnore()]
		public nodeVisible visible {
			get {
				return this.visibleField;
			}
			set {
				this.visibleField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string changeset {
			get {
				return this.changesetField;
			}
			set {
				this.changesetField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
		public string version {
			get {
				return this.versionField;
			}
			set {
				this.versionField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	[ComVisible(false)]
	public enum nodeVisible {
		
		/// <remarks/>
		@true,
		
		/// <remarks/>
		@false,
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
	[ComVisible(false)]
	public partial class osm {
		
		private object[] itemsField;
		
		private string versionField;
		
		private string generatorField;
		
		public osm() {
			this.versionField = "0.6";
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("api", typeof(api))]
		[System.Xml.Serialization.XmlElementAttribute("bounds", typeof(bounds))]
		[System.Xml.Serialization.XmlElementAttribute("changeset", typeof(changeset))]
		[System.Xml.Serialization.XmlElementAttribute("gpx_file", typeof(gpx_file))]
		[System.Xml.Serialization.XmlElementAttribute("node", typeof(node))]
		[System.Xml.Serialization.XmlElementAttribute("preferences", typeof(preferences))]
		[System.Xml.Serialization.XmlElementAttribute("relation", typeof(relation))]
		[System.Xml.Serialization.XmlElementAttribute("user", typeof(user))]
		[System.Xml.Serialization.XmlElementAttribute("way", typeof(way))]
		public object[] Items {
			get {
				return this.itemsField;
			}
			set {
				this.itemsField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string version {
			get {
				return this.versionField;
			}
			set {
				this.versionField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string generator {
			get {
				return this.generatorField;
			}
			set {
				this.generatorField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
	[ComVisible(false)]
	public partial class preferences {
		
		private tag[] tagField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("tag")]
		public tag[] tag {
			get {
				return this.tagField;
			}
			set {
				this.tagField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
	[ComVisible(false)]
	public partial class relation {
		
		private object[] itemsField;
		
		private string userField;
		
		private string uidField;
		
		private string timestampField;
		
		private string visibleField;
		
		private string changesetField;
		
		private string versionField;
		
		private string idField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("member", typeof(member))]
		[System.Xml.Serialization.XmlElementAttribute("tag", typeof(tag))]
		public object[] Items {
			get {
				return this.itemsField;
			}
			set {
				this.itemsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string id
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string user {
			get {
				return this.userField;
			}
			set {
				this.userField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string uid {
			get {
				return this.uidField;
			}
			set {
				this.uidField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string timestamp {
			get {
				return this.timestampField;
			}
			set {
				this.timestampField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnore()]
		public string visible {
			get {
				return this.visibleField;
			}
			set {
				this.visibleField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string changeset {
			get {
				return this.changesetField;
			}
			set {
				this.changesetField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
		public string version {
			get {
				return this.versionField;
			}
			set {
				this.versionField = value;
			}
		}
	
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
	[ComVisible(false)]
	public partial class user {
		
		private string descriptionField;
		
		private string[] languagesField;
		
		private home homeField;
		
		private string account_createdField;
		
		private string display_nameField;
		
		private string idField;
		
		/// <remarks/>
		public string description {
			get {
				return this.descriptionField;
			}
			set {
				this.descriptionField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute("lang", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
		public string[] languages {
			get {
				return this.languagesField;
			}
			set {
				this.languagesField = value;
			}
		}
		
		/// <remarks/>
		public home home {
			get {
				return this.homeField;
			}
			set {
				this.homeField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string account_created {
			get {
				return this.account_createdField;
			}
			set {
				this.account_createdField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string display_name {
			get {
				return this.display_nameField;
			}
			set {
				this.display_nameField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string id {
			get {
				return this.idField;
			}
			set {
				this.idField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
	[ComVisible(false)]
	public partial class way {
		
		private tag[] tagField;
		
		private nd[] ndField;
		
		private string userField;
		
		private string uidField;
		
		private string timestampField;
		
		private string versionField;
		
		private wayVisible visibleField;
		
		private string changesetField;
		
		private string idField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string id
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("nd")]
		public nd[] nd
		{
			get
			{
				return this.ndField;
			}
			set
			{
				this.ndField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("tag")]
		public tag[] tag {
			get {
				return this.tagField;
			}
			set {
				this.tagField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string user {
			get {
				return this.userField;
			}
			set {
				this.userField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string uid {
			get {
				return this.uidField;
			}
			set {
				this.uidField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string timestamp {
			get {
				return this.timestampField;
			}
			set {
				this.timestampField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
		public string version {
			get {
				return this.versionField;
			}
			set {
				this.versionField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnore()]
		public wayVisible visible {
			get {
				return this.visibleField;
			}
			set {
				this.visibleField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string changeset {
			get {
				return this.changesetField;
			}
			set {
				this.changesetField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	[ComVisible(false)]
	public enum wayVisible {
		
		/// <remarks/>
		@true,
		
		/// <remarks/>
		@false,
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
	[ComVisible(false)]
	public partial class osmChange {
		
		private object[] itemsField;
		
		private string versionField;
		
		private string generatorField;
		
		public osmChange() {
			this.versionField = "0.6";
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("create", typeof(create))]
		[System.Xml.Serialization.XmlElementAttribute("delete", typeof(delete))]
		[System.Xml.Serialization.XmlElementAttribute("modify", typeof(modify))]
		public object[] Items {
			get {
				return this.itemsField;
			}
			set {
				this.itemsField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string version {
			get {
				return this.versionField;
			}
			set {
				this.versionField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string generator {
			get {
				return this.generatorField;
			}
			set {
				this.generatorField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
	[ComVisible(false)]
	public partial class create {
		
		private object[] itemsField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("node", typeof(node))]
		[System.Xml.Serialization.XmlElementAttribute("relation", typeof(relation))]
		[System.Xml.Serialization.XmlElementAttribute("way", typeof(way))]
		public object[] Items {
			get {
				return this.itemsField;
			}
			set {
				this.itemsField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
	[ComVisible(false)]
	public partial class delete {
		
		private object[] itemsField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("node", typeof(node))]
		[System.Xml.Serialization.XmlElementAttribute("relation", typeof(relation))]
		[System.Xml.Serialization.XmlElementAttribute("way", typeof(way))]
		public object[] Items {
			get {
				return this.itemsField;
			}
			set {
				this.itemsField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
	[ComVisible(false)]
	public partial class modify {
		
		private object[] itemsField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("node", typeof(node))]
		[System.Xml.Serialization.XmlElementAttribute("relation", typeof(relation))]
		[System.Xml.Serialization.XmlElementAttribute("way", typeof(way))]
		public object[] Items {
			get {
				return this.itemsField;
			}
			set {
				this.itemsField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
	[ComVisible(false)]
	public partial class languages {
		
		private string[] langField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("lang", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string[] lang {
			get {
				return this.langField;
			}
			set {
				this.langField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
	[ComVisible(false)]
	public partial class diffResult {
		
		private object[] itemsField;
		
		private string generatorField;
		
		private string versionField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("node", typeof(diffResultNode), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[System.Xml.Serialization.XmlElementAttribute("relation", typeof(diffResultRelation), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[System.Xml.Serialization.XmlElementAttribute("way", typeof(diffResultWay), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public object[] Items {
			get {
				return this.itemsField;
			}
			set {
				this.itemsField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string generator {
			get {
				return this.generatorField;
			}
			set {
				this.generatorField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string version {
			get {
				return this.versionField;
			}
			set {
				this.versionField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	[ComVisible(false)]
	public partial class diffResultNode {
		
		private string old_idField;
		
		private string new_idField;
		
		private string new_versionField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string old_id {
			get {
				return this.old_idField;
			}
			set {
				this.old_idField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string new_id {
			get {
				return this.new_idField;
			}
			set {
				this.new_idField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string new_version {
			get {
				return this.new_versionField;
			}
			set {
				this.new_versionField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	[ComVisible(false)]
	public partial class diffResultRelation {
		
		private string old_idField;
		
		private string new_idField;
		
		private string new_versionField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string old_id {
			get {
				return this.old_idField;
			}
			set {
				this.old_idField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string new_id {
			get {
				return this.new_idField;
			}
			set {
				this.new_idField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string new_version {
			get {
				return this.new_versionField;
			}
			set {
				this.new_versionField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	[ComVisible(false)]
	public partial class diffResultWay {
		
		private string old_idField;
		
		private string new_idField;
		
		private string new_versionField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string old_id {
			get {
				return this.old_idField;
			}
			set {
				this.old_idField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string new_id {
			get {
				return this.new_idField;
			}
			set {
				this.new_idField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string new_version {
			get {
				return this.new_versionField;
			}
			set {
				this.new_versionField = value;
			}
		}
	}
}
